/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradeDisplayer;

public class App {

    public static void main(String[] args) {
    	GradeDB db = new GradeDBImpl();
    	GradeCollector collector = new GCollectorImpl();
    	collector.setDB(db);
    	GradeSorter sorter = new GradeSorterImpl();

    	GradeDisplayer main = new GradeDisplayer(db, collector, sorter);
    	main.setClassID(1);
    	main.go();
    }
}

