/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Covid19Test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Covid19Test {
    @Test
    void testCOVID19() throws Exception {
        COVID19 c = new COVID19();
        int[] real = new int[] { 1, 1, 1 };
        int[] diagnosis = new int[] { 1, 1, 1 };
        double[] expected = new double[] { 1, 1 };
        assertArrayEquals(expected, c.covid19(real, diagnosis));
    }

    @Test
    void testCOVID19b() throws Exception {
        COVID19 c = new COVID19();
        int[] real = new int[] { 0, 0, 0 };
        int[] diagnosis = new int[] { 1, 1, 1 };
        double[] expected = new double[] { 1, 0 };
        assertArrayEquals(expected, c.covid19(real, diagnosis));
    }

    @Test
    void testCOVID19c() throws Exception {
        COVID19 c = new COVID19();
        int[] real = new int[] { 1, 1, 1 };
        int[] diagnosis = new int[] { 0, 0, 0 };
        double[] expected = new double[] { 0, 1 };
        assertArrayEquals(expected, c.covid19(real, diagnosis));
    }

    @Test
    void testCOVID19d() throws Exception {
        COVID19 c = new COVID19();
        int[] real = new int[] { 1, 1, 1 };
        int[] diagnosis = new int[] { 1, 0, 0 };
        double[] expected = new double[] { 1.0 / 3, 1 };
        assertArrayEquals(expected, c.covid19(real, diagnosis));
    }

    @Test
    void testCOVID19e() throws Exception {
        COVID19 c = new COVID19();
        int[] real = new int[] { 1, 0, 1 };
        int[] diagnosis = new int[] { 0, 1, 1 };
        double[] expected = new double[] { 1.0 / 2, 1.0 / 2 };
        assertArrayEquals(expected, c.covid19(real, diagnosis));
    }

}
