/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_demo2;

public class App {
    public String getGreeting() {
        Add a = new Add();
        return "Hello World!" + String.valueOf(a.add(12,12));
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
