/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_demo2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AddTest {
    @Test void appHasAGreeting() {
        Add a = new Add();
        assertEquals(a.add(1, 2), 3);
    }
}
